select
-- FROM RAW_ORDER
    O.ORDER_ID
    , O.ORDER_DATE
    , O.SHIP_DATE
    , O.SHIP_MODE
    , O.ORDER_SELLING_PRICE
    , O.ORDER_COST_PRICE
-- FROM RAW_CUSTOMER
    , C.CUSTOMER_ID
    , C.CUSTOMERNAME
    , C.SEGMENT
    , C.COUNTRY
-- FROM RAW_PRODUCT
    , P.PRODUCTID
    , P.CATEGORY
    , P.PRODUCTNAME
    , P.SUBCATEGORY
    , (O.ORDER_SELLING_PRICE- O.ORDER_COST_PRICE) AS ORDER_PROFIT
from
{{ ref('RAW_ORDERS') }} AS O

LEFT JOIN 
{{ ref('RAW_CUSTOMER') }} AS C

ON 

O.CUSTOMER_ID = C.CUSTOMER_ID

LEFT JOIN
{{ ref('RAW_PRODUCT') }} AS P

ON

O.PRODUCT_ID = P.PRODUCTID


